name: Terraform CI

on:
  pull_request:
    branches:
      - main 

jobs:
  terraform-checks:
    name: pr-check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0" 

      - name: Initialize Terraform
        run: terraform init

      - name: Check Terraform Formatting
        run: terraform fmt -check -recursive

      - name: Validate Terraform Configuration
        run: terraform validate